CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_WATCHDOG=y
CONFIG_SERIAL=y
CONFIG_SERIAL_ESP32_USB=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_LOG=n
CONFIG_BOOT_BANNER=n
CONFIG_WIFI=n
CONFIG_BT=n
CONFIG_NETWORKING=n
CONFIG_PM=n
CONFIG_PM_DEVICE=n
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_ASSERT=y
CONFIG_REBOOT=y
